# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapplication', '0009_auto_20190602_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
